// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package services // import "github.com/tnakade/tno_exercise/app/proto/services"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBalanceRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{0}
}
func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(dst, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetBalanceResponse struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{1}
}
func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(dst, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type SendCoinRequest struct {
	FromUserId           uint64   `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId             uint64   `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCoinRequest) Reset()         { *m = SendCoinRequest{} }
func (m *SendCoinRequest) String() string { return proto.CompactTextString(m) }
func (*SendCoinRequest) ProtoMessage()    {}
func (*SendCoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{2}
}
func (m *SendCoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCoinRequest.Unmarshal(m, b)
}
func (m *SendCoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCoinRequest.Marshal(b, m, deterministic)
}
func (dst *SendCoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCoinRequest.Merge(dst, src)
}
func (m *SendCoinRequest) XXX_Size() int {
	return xxx_messageInfo_SendCoinRequest.Size(m)
}
func (m *SendCoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendCoinRequest proto.InternalMessageInfo

func (m *SendCoinRequest) GetFromUserId() uint64 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *SendCoinRequest) GetToUserId() uint64 {
	if m != nil {
		return m.ToUserId
	}
	return 0
}

func (m *SendCoinRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type SendCoinResponse struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCoinResponse) Reset()         { *m = SendCoinResponse{} }
func (m *SendCoinResponse) String() string { return proto.CompactTextString(m) }
func (*SendCoinResponse) ProtoMessage()    {}
func (*SendCoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{3}
}
func (m *SendCoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCoinResponse.Unmarshal(m, b)
}
func (m *SendCoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCoinResponse.Marshal(b, m, deterministic)
}
func (dst *SendCoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCoinResponse.Merge(dst, src)
}
func (m *SendCoinResponse) XXX_Size() int {
	return xxx_messageInfo_SendCoinResponse.Size(m)
}
func (m *SendCoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendCoinResponse proto.InternalMessageInfo

func (m *SendCoinResponse) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

type GetTransactionsRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionsRequest) Reset()         { *m = GetTransactionsRequest{} }
func (m *GetTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsRequest) ProtoMessage()    {}
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{4}
}
func (m *GetTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsRequest.Unmarshal(m, b)
}
func (m *GetTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsRequest.Merge(dst, src)
}
func (m *GetTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsRequest.Size(m)
}
func (m *GetTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsRequest proto.InternalMessageInfo

func (m *GetTransactionsRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetTransactionsResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTransactionsResponse) Reset()         { *m = GetTransactionsResponse{} }
func (m *GetTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionsResponse) ProtoMessage()    {}
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{5}
}
func (m *GetTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionsResponse.Unmarshal(m, b)
}
func (m *GetTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionsResponse.Merge(dst, src)
}
func (m *GetTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionsResponse.Size(m)
}
func (m *GetTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionsResponse proto.InternalMessageInfo

func (m *GetTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Abandoned            string   `protobuf:"bytes,3,opt,name=abandoned,proto3" json:"abandoned,omitempty"`
	ReceivedAccount      string   `protobuf:"bytes,4,opt,name=received_account,json=receivedAccount,proto3" json:"received_account,omitempty"`
	ReceivedAddress      string   `protobuf:"bytes,5,opt,name=received_address,json=receivedAddress,proto3" json:"received_address,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_50a515b16e66819c, []int{6}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Transaction) GetAbandoned() string {
	if m != nil {
		return m.Abandoned
	}
	return ""
}

func (m *Transaction) GetReceivedAccount() string {
	if m != nil {
		return m.ReceivedAccount
	}
	return ""
}

func (m *Transaction) GetReceivedAddress() string {
	if m != nil {
		return m.ReceivedAddress
	}
	return ""
}

func (m *Transaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBalanceRequest)(nil), "services.GetBalanceRequest")
	proto.RegisterType((*GetBalanceResponse)(nil), "services.GetBalanceResponse")
	proto.RegisterType((*SendCoinRequest)(nil), "services.SendCoinRequest")
	proto.RegisterType((*SendCoinResponse)(nil), "services.SendCoinResponse")
	proto.RegisterType((*GetTransactionsRequest)(nil), "services.GetTransactionsRequest")
	proto.RegisterType((*GetTransactionsResponse)(nil), "services.GetTransactionsResponse")
	proto.RegisterType((*Transaction)(nil), "services.Transaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletClient interface {
	// ログイン情報取得
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	SendCoin(ctx context.Context, in *SendCoinRequest, opts ...grpc.CallOption) (*SendCoinResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
}

type walletClient struct {
	cc *grpc.ClientConn
}

func NewWalletClient(cc *grpc.ClientConn) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/services.Wallet/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SendCoin(ctx context.Context, in *SendCoinRequest, opts ...grpc.CallOption) (*SendCoinResponse, error) {
	out := new(SendCoinResponse)
	err := c.cc.Invoke(ctx, "/services.Wallet/SendCoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, "/services.Wallet/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
type WalletServer interface {
	// ログイン情報取得
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	SendCoin(context.Context, *SendCoinRequest) (*SendCoinResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
}

func RegisterWalletServer(s *grpc.Server, srv WalletServer) {
	s.RegisterService(&_Wallet_serviceDesc, srv)
}

func _Wallet_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Wallet/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SendCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SendCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Wallet/SendCoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SendCoin(ctx, req.(*SendCoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Wallet/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _Wallet_GetBalance_Handler,
		},
		{
			MethodName: "SendCoin",
			Handler:    _Wallet_SendCoin_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _Wallet_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_50a515b16e66819c) }

var fileDescriptor_service_50a515b16e66819c = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0xdd, 0xc8, 0xda, 0xb3, 0x9f, 0x0e, 0x4b, 0x6c, 0x21, 0xf4, 0xa2, 0x44, 0x42, 0x1a,
	0x12, 0x4a, 0x44, 0xe1, 0x66, 0x97, 0x6c, 0x17, 0x53, 0x6f, 0xc3, 0x10, 0x88, 0x9b, 0xca, 0xb5,
	0x0f, 0xc3, 0xa2, 0xb5, 0x83, 0xed, 0x4c, 0xf0, 0x80, 0xbc, 0x10, 0x4f, 0x80, 0xe6, 0xc4, 0xf9,
	0x69, 0x2b, 0xb8, 0xfc, 0x7e, 0x72, 0x3e, 0xeb, 0x3b, 0x27, 0x70, 0x6c, 0x50, 0xdf, 0x0b, 0x86,
	0x69, 0xa1, 0x95, 0x55, 0x64, 0x58, 0x43, 0x93, 0xbc, 0x86, 0x27, 0x37, 0x68, 0xaf, 0xe8, 0x8a,
	0x4a, 0x86, 0x39, 0xfe, 0x28, 0xd1, 0x58, 0x72, 0x0e, 0x07, 0xa5, 0x41, 0xbd, 0x10, 0x3c, 0x0a,
	0xa6, 0xc1, 0xc5, 0x7e, 0x1e, 0x3e, 0xc0, 0x39, 0x4f, 0x52, 0x20, 0x5d, 0xb7, 0x29, 0x94, 0x34,
	0x48, 0x22, 0x38, 0x58, 0x56, 0x94, 0xb3, 0x8f, 0x72, 0x0f, 0x13, 0x01, 0xe3, 0x0f, 0x28, 0xf9,
	0xb5, 0x12, 0xd2, 0xcf, 0x9e, 0xc2, 0xd1, 0x57, 0xad, 0xd6, 0x8b, 0x7e, 0x00, 0x3c, 0x70, 0x1f,
	0x5d, 0x08, 0x99, 0x00, 0x58, 0xd5, 0xe8, 0x03, 0xa7, 0x0f, 0xad, 0xaa, 0xd5, 0x33, 0x08, 0xe9,
	0x5a, 0x95, 0xd2, 0x46, 0x7b, 0x2e, 0xab, 0x46, 0xc9, 0x25, 0x9c, 0xb6, 0x51, 0xf5, 0xc3, 0x5e,
	0xc2, 0x89, 0xd5, 0x54, 0x1a, 0xca, 0xac, 0x50, 0xd2, 0xa7, 0x8d, 0xf2, 0xe3, 0x0e, 0x3b, 0xe7,
	0xc9, 0x1b, 0x38, 0xbb, 0x41, 0x7b, 0xdb, 0x72, 0xe6, 0xbf, 0x45, 0xdc, 0xc2, 0xf9, 0xd6, 0x27,
	0x75, 0xe8, 0x25, 0x1c, 0x75, 0xc6, 0x9b, 0x28, 0x98, 0xee, 0x5d, 0x1c, 0xce, 0x9e, 0xa6, 0xbe,
	0xf2, 0xb4, 0xf3, 0x55, 0xde, 0xb3, 0x26, 0xbf, 0x03, 0x38, 0xec, 0xa8, 0xe4, 0x04, 0x06, 0xcd,
	0x9b, 0x07, 0x82, 0x93, 0x18, 0x86, 0x8c, 0x5a, 0xbc, 0x53, 0xfa, 0x97, 0xeb, 0x65, 0x94, 0x37,
	0x98, 0x4c, 0x60, 0x44, 0x97, 0x54, 0x72, 0x25, 0x91, 0xd7, 0xd5, 0xb4, 0x04, 0x79, 0x05, 0xa7,
	0x1a, 0x19, 0x8a, 0x7b, 0xe4, 0x0b, 0xca, 0x98, 0xeb, 0x6f, 0xdf, 0x99, 0xc6, 0x9e, 0x7f, 0x5f,
	0xd1, 0x7d, 0x2b, 0xe7, 0x1a, 0x8d, 0x89, 0x1e, 0x6f, 0x58, 0x2b, 0xba, 0xb3, 0x8b, 0xb0, 0xbb,
	0x8b, 0xd9, 0x9f, 0x00, 0xc2, 0x4f, 0x74, 0xb5, 0x42, 0x4b, 0xe6, 0x00, 0xed, 0xc5, 0x90, 0xe7,
	0x6d, 0x0b, 0x5b, 0x57, 0x17, 0x4f, 0x76, 0x8b, 0x55, 0xad, 0xc9, 0x23, 0x72, 0x0d, 0x43, 0xbf,
	0x61, 0xf2, 0xac, 0xf5, 0x6e, 0x1c, 0x58, 0x1c, 0xef, 0x92, 0x9a, 0x21, 0x9f, 0x61, 0xbc, 0xb1,
	0x38, 0x32, 0xed, 0xe5, 0xee, 0x38, 0x83, 0xf8, 0xc5, 0x3f, 0x1c, 0x7e, 0xf2, 0xd5, 0xbb, 0x2f,
	0xb3, 0x3b, 0x61, 0xbf, 0x95, 0xcb, 0x94, 0xa9, 0x75, 0x66, 0x25, 0xfd, 0x4e, 0x39, 0x66, 0x56,
	0xaa, 0x05, 0xfe, 0x44, 0xcd, 0x84, 0xc1, 0x8c, 0x16, 0x45, 0xe6, 0x7e, 0xc0, 0xcc, 0xcf, 0x5b,
	0x86, 0x0e, 0xbf, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x48, 0xad, 0x1a, 0xbc, 0xa1, 0x03, 0x00,
	0x00,
}
